apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-restored
  namespace: postgres
spec:
  instances: 1
  storage:
    size: 2Gi
  bootstrap:
    recovery:
      backup:
        name: pg-cluster-backup-2
