apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-store
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      version: "v1"
      auth:
        tokenSecretRef:
          name: openbao-token
          namespace: external-secrets
          key: token
